server:
  port: 8761
spring:
  application:
    name: discoveryserver

eureka:
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 2
  server:
    eviction-interval-timer-in-ms: 1000
    response-cache-update-interval-ms: 1000
  client:
    register-with-eureka: false
    fetch-registry: false

